In [3]:
import numpy as np
import pandas as pd

In [20]:
with open("../Data/sentences.txt", "r") as file:
    contents = file.readlines()  #считал все строки в лист

In [21]:
contents

['In comparison to dogs, cats have not undergone major changes during the domestication process.\n',
 'As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.\n',
 'A common interactive use of cat for a single file is to output the content of a file to standard output.\n',
 'Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.\n',
 'In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.\n',
 'The domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.\n',
 'Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).\n',
 'However, if the output is piped or redirected, cat is unnecessary.\n',
 'cat with one named file is safer whe

In [25]:
for i in range(len(contents)):
    contents[i] = str(contents[i]).lower()  # все буквы привел к нижнему регистру

In [53]:
import re
str_to_del = ['']
val_to_del = str_to_del[0]
new_contents = []
for i in range(len(contents)):
    new_contents.append(re.split('[^a-z]', str(contents[i]))) # удаление всех ненужных символов и сохранение всех слов в список
    new_contents[i] = [x for x in new_contents[i] if x != ''] # удаляем пробелы из списка

In [72]:
# Составьте список всех слов, встречающихся в предложениях. 
# Сопоставьте каждому слову индекс от нуля до (d - 1), где d — число различных слов в предложениях. 
# Для этого удобно воспользоваться структурой dict.
my_dict = {}
temp_set = set()
for i in range(len(new_contents)):
    temp_set.update(set(list(new_contents[i])))  # создал множество встречающихся слов

In [84]:
# функция, которая будет считать количество слов по всем строкам списка
def word_count(word):
    numbers = 0
    for i in range(len(new_contents)):
        numbers = numbers + new_contents[i].count(word)
        
    return numbers

In [85]:
# создаем словарь
for i in temp_set:
    my_dict[i] = word_count(i)

In [89]:
print(len(my_dict))

254


In [90]:
print(len(new_contents))

22


In [94]:
my_matrix = np.zeros([22, 254])

In [96]:
my_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [99]:
# my_sec_dict  - сделал словарь с индексами слов
i = 0
my_sec_dict = {}
for item in my_dict:
    my_sec_dict[item] = i
    i += 1
    

In [122]:
# теперь надо заполнить матрицу
for i in range(len(contents)):
    for j in new_contents[i]:
        k = my_sec_dict[j] # из второго словаря берем позицию для столбца
        val = new_contents[i].count(j) # из первого столбца берем значение(количество этих слов) для ячейки
        my_matrix[i][k] = val

In [123]:
print(my_matrix)

[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 1. 1. 0.]
 [0. 2. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]]


Найдите косинусное расстояние от предложения в самой первой строке (In comparison to dogs, cats have not undergone...) до всех остальных с помощью функции scipy.spatial.distance.cosine. Какие номера у двух предложений, ближайших к нему по этому расстоянию (строки нумеруются с нуля)? Эти два числа и будут ответами на задание. Само предложение (In comparison to dogs, cats have not undergone... ) имеет индекс 0.

In [110]:
from scipy.spatial.distance import cosine

In [124]:
dists = []
for row in my_matrix:
    dists.append(cosine(row, my_matrix[0,:]))

In [125]:
dists

[0.0,
 0.9527544408738466,
 0.8644738145642124,
 0.8951715163278082,
 0.7770887149698589,
 0.9402385695332803,
 0.7327387580875756,
 0.9258750683338899,
 0.8842724875284311,
 0.9055088817476932,
 0.8328165362273942,
 0.8804771390665607,
 0.8396432548525454,
 0.8703592552895671,
 0.8740118423302576,
 0.9442721787424647,
 0.8406361854220809,
 0.956644501523794,
 0.9442721787424647,
 0.8885443574849294,
 0.8427572744917122,
 0.8250364469440588]

In [133]:
print(contents[0])
print(contents[4])
print(contents[6])

in comparison to dogs, cats have not undergone major changes during the domestication process.

in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.

domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).



In [132]:
dists.index(max(dists))

17

максимальные значения у строк с индексами 1 и 17